[profile.release]
panic = 'unwind'

[workspace]
members = [
    'cli',
    'executor',
    'inspect',
    'primitives',
    'rpc',
    'rpc-client',
    'runtime',
    'testing',
    'transaction-factory',
]
